# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - BharatBazar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install requires
        run: |
          wget http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
          tar -xf pa_stable_v19_20140130.tgz
          cd portaudio/
          ./configure
          make clean
          make
          sudo make install
          sudo apt install build-essential portaudio19-dev
          sudo apt-get install portaudio19-dev python-all-dev
          sudo pip3 install pyaudio
          sudo apt-get install python3-pyaudio

          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DB8658361F742BF80332E812B873F7E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_992A333BAF074F53B5857E5A1CBE303B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_460CC493CC17446CBD1496DB8BE6E8CD }}

      - name: Install require
        run: |
          wget http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
          tar -xf pa_stable_v19_20140130.tgz
          cd portaudio/
          ./configure
          make clean
          make
          sudo make install
          sudo apt install build-essential portaudio19-dev
          sudo apt-get install portaudio19-dev python-all-dev
          sudo pip3 install pyaudio
          sudo apt-get install python3-pyaudio

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'BharatBazar'
          slot-name: 'Production'
          
